### ISSUE TITLE
Template subsystem

### ISSUE THREAD

**Issue by palikhov** [UnicornHeartClub/Issues#211] opened 2018-02-15 13:00 UTC
0. template is specific to used character sheet which are specific to used system
🔽
1. PowerVTT is designed for using with dnd 5e firstly..
🔽
FOR Release version PowerVTT must already have:

some basic chat template - independent from character sheet

and power-5e-default template - so power, complex and functional as possible. Power-5e-default is discussed in https://github.com/UnicornHeartClub/Issues/issues/133

**Comment by Aquaricat** [comment] 2018-02-15 13:07
This is a duplicate of #133.

**Closed by Aquaricat** 2018-02-15 13:07 UTC
